apiVersion: v1
kind: Service
metadata:
  name: apiserv
spec:
  type: NodePort
  selector:
    app: apidepl 
    
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001
    protocol: TCP
    
