apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-sfs
spec:
  selector:
    matchLabels:
      app: mysql-a # has to match .spec.template.metadata.labels
  serviceName: "postgresql-svc"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: mysql-a # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql-db
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 3306
          name: mysql-port
        volumeMounts:
        - name: mysqldata
          mountPath: /var/lib/mysql
      volumes:
        -  name: mysqldata
           persistentVolumeClaim:
            claimName:  mypvc
  