apiVersion: v1
kind: PersistentVolume
metadata:
  name: fepv
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: hostpath
  hostPath:
    path: "/usr/src/app"
   