apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fepvc
spec:
  storageClassName: hostpath
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
