apiVersion: v1
kind: Service
metadata:
  name: myfeserv
spec:
  type: NodePort
  selector:
    app: fedpl 
    
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
    protocol: TCP
    
